name: Webapp build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.17]

    steps:
      # Vérification du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      # Mise a jour de npm 
      - name: Update npm to match local version
        run: npm install -g npm@11.1.0

      # Installation des dépendances avec npm clean-install
      - name: Install dependencies
        run: npm ci

      # Audit de sécurité
      - name: Audit
        run: npm audit

      # Vérification de la signature des audits
      - name: Audit Signature
        run: npm audit signatures

      # Linter
      - name: Lint
        run: npm run lint

      # Set environment variables
      - name: Create environment file
        run: |
          mkdir src/environments
          echo "Creating production environment file..."
          echo "${{ secrets.FIREBASE_CONFIG }}" >> src/environments/environment.ts
      
      # Tests
      - name: Test
        run: npm run test:ci

      # Build
      - name: Build
        run: npm run build